# Generated by Django 3.2.3 on 2021-07-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffregistration',
            old_name='user',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='studentregistration',
            old_name='user',
            new_name='student',
        ),
    ]
